name: flutter_staggered_grid_view
description: A Flutter staggered grid view (masonry tiles) which supports multiple columns with rows of varying sizes.
version: 1.0.0
homepage: https://github.com/letsar/flutter_staggered_grid_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter