name: flutter_staggered_grid_view
description: A Flutter staggered grid view
version: 0.1.1
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/flutter_staggered_grid_view
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <2.0.0"
  flutter: "^0.1.0"